name: Repack

on: [push]

jobs:
  build-MiSTer-pack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Re-generate MiSTer SMDB.txt
      run: |
        rm -f EverDrive\ Pack\ SMDBs/MiSTer\ SMDB.txt
        cat EverDrive\ Pack\ SMDBs/*.txt | awk -f build_MiSTer_SMBD.awk > EverDrive\ Pack\ SMDBs/MiSTer\ SMDB.txt
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v2.5.0
      with:
        # Commit message
        commit_message: Rebuild "MiSTer SMDB.txt"
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
